/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  swotSidebar: [
    'intro',
    {
      type: 'category',
      label: '📊 SWOT-анализы',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'swot'}],
    },
    {
      type: 'category', 
      label: '🔄 Сравнения',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'comparisons'}],
    },
  ],
};

export default sidebars;
